### ISSUE TITLE
Allow craftr generator artifacts be outside the sources 

### ISSUE THREAD

**Issue by winksaville** [craftr-build/craftr#10]
With other meta build systems, such as meson, you can have the "build" directory outside of the source tree. This means you never modify the source tree, which I find convenient.

So I'd like to be able to do the following:

```
$ ./gen_srcs craftr test 1 1
$ mkdir build
$ cd build
$ craftr export ../test
```
Another idiom is the "build" directory is inside the source tree but all artifacts are just inside that directory.
```
$ ./gen_srcs craftr test 1 1
$ cd test
$ mkdir build
$ cd build
$ craftr export ..
```

**Comment by NiklasRosenstein** [comment]
Regarding your second example, the build directory inside the source tree but all artifacts are just inside that directory, that is already the case in the [gen_srcs](https://github.com/winksaville/gen_srcs) example.  As it stands now, the build directory depends on how you've set it up in the Craftr file.

```python
build_dir = join(project_dir, 'build')
objects = move(sources, project_dir, build_dir, suffix='o')
```

You can set up a module to response to a global override build directory like this:

```python
setdefault('build_dir', join(project_dir, 'build'))
objects = move(sources, project_dir, build_dir, suffix='o')
```

For instance, if you want to build outside the source tree, you need to

1. make sure Craftr can find the module (talking about the `Craftfile`/`.craftr` file)
2. override the `build_dir` setting globally for the output directory
  

    ~/Desktop/test $ cd ../build
    ~/Desktop/build $ export CRAFTR_PATH=../test
    ~/Desktop/build $ craftr -m hierarchy -D:build_dir=.

I don't know what the "standard" or "preferred" way to this is, but from where I come from, or at least from the workflow that I developed, I usually want to switch my current working directory as little as possible and operate from the source root. So the above would translate to

    ~/Desktop/test $ craftr -D:build_dir=../build

**Comment by winksaville** [comment]
I guess I tend to have multiple windows/apps open and don't switch dirs
that often. What I do like is to be able to delete one directory to do a
full clean. So, IMHO, working in the source tree is rarely a good choice in
a large project.

**Comment by NiklasRosenstein** [comment]
Sorry, I don't understand your point. Even if you're at the source tree with creator, the build still happens in the build directory of your choice.

**Comment by winksaville** [comment]
So lets say I want to have both a debug build dir  and a release build dir
as two different directories. Having an option for craftr to create two
different build.ninja files in two different directories would be what I'd
want.

**Comment by NiklasRosenstein** [comment]
I see. A feature of Creator was the `NinjaOut` macro. If you had that set, it would specify the output file of the ninja export, if not explicitly specified via the command line. You could do something like this (not yet implemented in Craftr).

```python
mode = 'debug' if debug else 'release'
build_dir = join(project_dir, 'build-' + mode)
ninja_out = join(build_dir, 'build.ninja')
```

And then do

    craftr -D:debug export
    ninja -f build-debug/build.ninja

But I no longer thing this is actually a good idea. Since Craftr uses the `Craftfile` of the current directory if no module name was specified via `-m/--module`, it might be a good idea to add an option to override the "main" directory.

    cd build
    craftr -c .. export

That could be combined with a feature that I want to implement for Craftr as well and that was
available in Creator. It would allow you to create a `.creator_profile` file in a directory and if that file is encountered in your home path and/or your current working directory, it would be executed before anything else.

    my_project $ cat build/.craftr_profile
    G.debug = False
    my_project $ cat build/.craftr_profile
    G.debug = True

**Comment by winksaville** [comment]
Sounds like it will be possible one way or another, but in the future it
would be nice to support what both CMake and Meson do as a default, which
is what I explained. But their are probably bigger fish to fry right now :)
