### ISSUE TITLE
PyPI files have CRLF line terminators

### ISSUE THREAD

**Issue by dfroger** [craftr-build/craftr#106]
When  installing from PyPy:

    $ pip install craftr-build

Files installed are:

    Python script, ASCII text executable, with CRLF line terminators

and invoking `craftr` on GNU/Linux fails with:

        /usr/bin/env: 'python3\r': No such file or directory

However, installing from GitHub repo works and is fine for me, I'll use this way.

**Comment by NiklasRosenstein** [comment]
Thanks for submitting this issue. I'll look into it!

To be honest, I don't test a lot on Linux as I'm bound to using Windows and Mac for my work and I also use installations from the repository since Craftr is still a very early project and I usually update it as need arises. :) So thanks again for testing!

**Comment by NiklasRosenstein** [comment]
Btw. as I mentioned in the other issue, the current version is much different (in terms of command-line and file names) compared to `v1.0.3` on PyPI, so since you're using the installation form the Git repository now anyway, I highly recommend using the latest version from the `master` branch. :)

**Comment by NiklasRosenstein** [comment]
I just changed the title slightly, PyPy is another Python implementation like CPython, Jython or IPython. PyPI is the Python Package Index. :)

**Comment by dfroger** [comment]
Thanks for changing the title! 

Indeed, this issue is really not blocking for me, I opened just as a remainder.

**Comment by NiklasRosenstein** [comment]
I think the problem comes from me generating the Python source distribution on Windows where the files have Windows lines endings due to Git autocrlf.

**Comment by NiklasRosenstein** [comment]
I'll create the source distributions for PyPI from a Linux machine now, that will make it work on both Unix and Windows environments. I just submitted [Craftr v1.1.0](https://pypi.python.org/pypi/craftr-build) to PyPI.
