### ISSUE TITLE
configure and install

### ISSUE THREAD

**Issue by dfroger** [craftr-build/craftr#117]
Hello Niklas,

This is not to open issue, just a general question about `Craftr`.

There are usally 3 steps using a build system (or 4 with `test`):
- `configure`
- `build`
- `install`

Does `Craftr` focus on these 3 steps, or only on the `build` step?

`install` is just installing the software in the system or in some `prefix`. Especially, can `Craftr` do the job of a `setup.py`?

`configure` can be for example checking:
- A C header is found.
- A C library is found.
- The version number of a dependency.

This may involve compiling a snippet of code. For example, the section in the [Waf documentation](https://waf.io/book/#_configuration_helpers).

**Comment by NiklasRosenstein** [comment]
Hey David,

> Does `Craftr` focus on these 3 steps, or only on the `build` step?

Craftr is intended to focus on the `configure` and `build` step and intents to do both at the same time.

> `configure` can be for example checking:
- A C header is found.
- A C library is found.
- The version number of a dependency.

Currently, dependencies in Craftr are largely

**Comment by NiklasRosenstein** [comment]
Note: updated previous comment.

**Comment by NiklasRosenstein** [comment]
#134 and #135 are related to this.
