### ISSUE TITLE
suffix() argument replace instead of append

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#12]
An argument called `replace` rather than `append` for the `suffix()` function might be better suited and more self documenting.

**Comment by winksaville** [comment]
How about both?

**Comment by NiklasRosenstein** [comment]
Both wouldn't make much sense, what would it do without an argument? And assuming replacing the suffix would be the default value:

```python
def suffix(filename, text, replace=True, append=False):
    # ...
```

What would happen if you pass `suffix(filename, 'o', append=True)`? The function would have both `replace` and `append` set to True.

**Comment by winksaville** [comment]
I was assuming a named arg was always required. It would seem then the
method should be called replaceSuffix otherwise the its unclear what it
means, in fact it could be return the current suffix.

**Comment by NiklasRosenstein** [comment]
I was thinking about the action "to suffix" or "to prefix" something. But I guess using "replace_suffix" and "add_suffix" or "append_suffix" would suite better.

**Comment by winksaville** [comment]
I'd go with append/replace.

**Comment by NiklasRosenstein** [comment]
Or maybe with `rmsuffix` and `addsuffix`? Then you could do `addsuffix(rmsuffix(files), 'o')` instead of `replacesuffix(files, 'o')`. The reason why I think about doing this is we would need distinct functions in the `platform` modules as well, like `add_obj()` and `replace_obj()`.

**Comment by NiklasRosenstein** [comment]
To be consistent, `addprefix()` would need to really add the text to the beginning of the string. `addbaseprefix()` would then do the job of prepending the text to the files basename.

**Comment by winksaville** [comment]
Personally I'd go with remove instead of rm, but if you like short names
I'd go with rmv. As for replace do addnit if you find addXxx(rmvXxx) is
common.

Another consideration is should authors of Craftrnfiles be required to
specify the suffixes. I'd say know as its platform specific. So should be
something done by implementors of compiler modules, correct?

**Comment by NiklasRosenstein** [comment]
I've settled with `addprefix()` being as it used to be, it will add a prefix to the base of the filename (as would make the most sense in most cases I can think of), `addsuffix()` now simply appends, but in case you're naughty you can still pass `replace=True` to instruct it to replace the suffix instead of append it. `rmvsuffix()` will remove all file suffixes.

**Comment by winksaville** [comment]
SG
