### ISSUE TITLE
Error "unused options for compile(): {'program'}" even though the option is used

### ISSUE THREAD

**Issue by tliron** [craftr-build/craftr#125]
The option is supported by compilers and is used in Ninja, so this warning must be wrong.

**Comment by NiklasRosenstein** [comment]
Hey could you please show me the Craftfile? Thanks :)

**Comment by NiklasRosenstein** [comment]
Nvm. compile() doesn't take a "program" argument. You have to pass objects created by compile() to link(), which does take a

**Comment by tliron** [comment]
I can't show the whole file, but it's this part:
```
cpp_objects = platform.cc.compile(
    sources=cpp_sources,
    include=include,
    program='%s-g++' % hosts[host],
    additional_flags=cppflags)
```

**Comment by NiklasRosenstein** [comment]
Thanks, I can confirm your issue. I'm currently in vacation, but I'll look into it soonish.

I would appreciate if you can share your/any project that you use Craftr with, but I can understand if you are using it for a private project. :)

**Comment by tliron** [comment]
I promise I will share in the future. :)

Thank you so much for this project, by the way, as it fulfills my need perfectly: an easy Python frontend around Ninja. I tried Meson before Craftr, but was disappointed by how much they hardcoded into it, also with too many abstractions from the command line.

I do have some ideas for improvements to Craftr, will likely send pull requests in the near future. Also, the "magic" Python stuff has been giving me some headaches, there might be ways to make it less intrusive.

Enjoy your vacation.

**Comment by NiklasRosenstein** [comment]
I can no longer reproduce this in Craftr 2.x. Please re-open if you hit the issue again. Will not be fixed for Craftr 1.

I'm glad that you like Craftr! I hope you like what's coming into the new Craftr 2.x! I'm more than happy to review any contributions you want to make and would like to hear about your issues with the Python magic. :)

Cheers
