### ISSUE TITLE
No way to disable '-O' flag for compilers

### ISSUE THREAD

**Issue by tliron** [craftr-build/craftr#126]
In my build, I add the `-O` flag programmatically based on certain logic. However, Craftr will _always_ set the `-O` flag due to [this code](https://github.com/craftr-build/craftr/blob/master/craftr/lib/craftr.ext.compiler.llvm.py#L242).

In my opinion, if the `optimize` argument is None, then Craftr shouldn't do anything. The "none" string value could indeed continue have the meaning of `-O0`.

This change would also allow users to use other `-O` flags, such as `-O3`.

**Comment by NiklasRosenstein** [comment]
Thanks for the hint. What you describe is usually the pattern I was
following, but apparently I missed out here. You can send a PR, otherwise
I'll fix it soon and have a look at the other flags to make sure the
behaviour is consistent.

Cheers :)
Niklas

**Comment by tliron** [comment]
No rush at all!

According to the gcc documentation, if you have more than one `-O` flag then the later one takes precedence, so this doesn't affect my functionality. But it could be confusing to see more than `-O` flag in the Ninja commands.
