### ISSUE TITLE
Allow setting path to Ninja executable

### ISSUE THREAD

**Issue by tliron** [craftr-build/craftr#127]
It would be nice if there were an optional for this! `--ninja-path` or similar.

The use case is embedding Craftr in bigger build systems (Debian, Eclipse) where you have some sort of contained filesystem or limited access to the environment path.

**Comment by NiklasRosenstein** [comment]
You can do that in Craftr 2.x in 2 different ways: Either set the `craftr.ninja` option or the` NINJA` environment variable. To set the option, you can use the `-d` command-line parameter like

    $ craftr -d craftr.ninja=ninja-1.7.2.git.exe 

Or define it in a configuration file.

```ini
[craftr]
ninja = ninja-1.7.2.git.exe
```

Will not be fixed in Craftr 1.
