### ISSUE TITLE
nr.utils dependency not available

### ISSUE THREAD

**Issue by tliron** [craftr-build/craftr#130]
This happens with both the PyPI version and git master:
```
  Could not find a version that satisfies the requirement nr.utils==1.0 (from craftr-build==1.1.2) (from versions: )
No matching distribution found for nr.utils==1.0 (from craftr-build==1.1.2)
```

**Comment by NiklasRosenstein** [comment]
Hey, thanks for reporting this issue. Big mistake on my part. In the process of working on Craftr 2 I renamed the library to just "nr" from "nr.utils" but forgot that it will break Pip installs.
