### ISSUE TITLE
Minor tweaks to README.md

### ISSUE THREAD

**Issue by winksaville** [craftr-build/craftr#140]
I thought it a good idea to have the c source in the README.md and changed the build sentence, see #139.

**Comment by NiklasRosenstein** [comment]
Thanks! Merged

**Comment by NiklasRosenstein** [comment]
PS:  You don't need to open a separate issue, a PR is basically one already. :)

**Comment by winksaville** [comment]
OK, I wasn't sure what your policy and better safe than sorry :)
