### ISSUE TITLE
Craftr 2: gcc_compile_additional_flags and gcc_link_additional_flags no longer work

### ISSUE THREAD

**Issue by tliron** [craftr-build/craftr#150]
For example, this worked in Craftr 1, but is no longer accepted:
```
objects = c_compile(
    sources=sources,
    include=include,
    frameworks=frameworks,
    std='c11',
    pic=is_linux,
    gcc_compile_additional_flags=cflags)
```
My frameworks also add these arguments!

**Comment by NiklasRosenstein** [comment]
Even worse, it moved into the link() section 🙈 I removed them for a few iterations, but quickly noticed that the arguments are actually quite useful, though apparently I failed re-adding them to the Gcc/Clang backends.

---

Btw. in case that is interesting for you, new in Craftr 2 are prepare-callbacks. (Also an undocumented feature for the time begin :( ). It's a quite "deep" feature though that I needed for an edgy case ([NiklasRosenstein.maxon.c4d](https://github.com/craftr-build/NiklasRosenstein.maxon.c4d/blob/51d9523a588d8b21ad04d4d7f1a6dbad173147fb/sdk.py#L96)).

Probably a bit too "heavy" in terms of the amount of code required for your simple use case.

```python
def compile_callback(compiler, builder):
  if compiler.name == 'msvc':
    builder.setdefault('msvc_runtime_library', 'static')
  elif compiler.name == 'clang-cl':
    # ...
  elif compiler.name == 'gcc':
    builder.add_local_framework(additional_flags=cflags)
  elif compiler.name == 'llvm':
    # ...

objects = c_compile(
  # ...
  cxc_compile_prepare_callbacks = [compile_callback]
)
```

**Comment by NiklasRosenstein** [comment]
Again, can be found in the development branch. Please check and confirm if it works again :)

**Comment by tliron** [comment]
Good job. :) For the first time, my rather complex project is compiling with Craftr 2.

**Comment by NiklasRosenstein** [comment]
Yeay! Happy to hear that :)
