### ISSUE TITLE
Illegal ninja.build files can be created by Craftr

### ISSUE THREAD

**Issue by tliron** [craftr-build/craftr#151]
This took me a while to debug. :) But I found that if you have a `c_compile` statement when the `inputs` arg is an empty list, then Craftr will go ahead and create a `ninja.build` file for that target, but with no build rules. Unfortunately Ninja chokes on this and display a very unhelpful error. I think it would be best if Craftr simply excluded empty targets from builds, or at the very least displayed a friendly error message.

**Comment by NiklasRosenstein** [comment]
Aye, sorry about that. I've noticed that myself a few times already but didn't come around to write a fix/issue for it. Actually I was thinking of throwing a fatal error when there are no inputs for such targets. Do  you know cases where you wouldn't want a fatal error but instead the target being ignored?

**Comment by tliron** [comment]
Yes, I have such a case. :) I'm doing a cross-build whereby for
Windows-only I need to compile some files in c++. For Linux and other
builds, the files are empty. (I generate the list of these files via some
Python code.)

It's easy to workaround this issue - I just need a few "if" statements. But
it would be nice if Craftr handled this implicitly.

**Comment by tliron** [comment]
Hi Niklas, sorry for using this issue for something different -- just wanted to thank you again for your work on Craftr. I have decided that I need to go back to basics and write my own build system: [Rōnin](https://github.com/tliron/ronin) (Apache license). It tries to do things much more simply than Craftr, and it likely will never be as powerful, but I just need a tool that does what I want it to do. :)

Thank you for showing me that a Python frontend for Ninja is a great idea!

**Comment by NiklasRosenstein** [comment]
Found the issue, it is caused by the fact that only a `rule` is exported for the source compilation, but not `build` instruction since there are no files to be built. Thinking about some way to fix that without yielding an error in Craftr.

I'd love to hear what Craftr didn't do for you, so I can improve on it. :)

Cheers

**Comment by tliron** [comment]
Thanks, Niklas! The issue is that to my taste you moved too far away from
standard Python programs, with specialized ways of importing modules, using
the equal operator to set names (breaking various cases when you don't do a
left-hand assignment), and in Craftr 2.0 the additional requirement of JSON
descriptors. I felt that I had to read too much documentation and look
through too much code to accomplish simple things. My recommendation is to
go back to the basics and establish for yourself clearly what are your
goals for Craftr.

**Comment by NiklasRosenstein** [comment]
I think have I a pretty clear goal in mind for Craftr. I am thinking about making the manifest not mandatory, but its required as soon as you want to re-use a module or want "simple" option handling (you could just read `session.options` but that's less convenient than having the option values existing in the `options` namespace with the correct type). For the loading part, the way Craftr 1 loaded modules had a number of limitations that would restrict the progress in the direction that I want to push Craftr to. 

I think apart from the `load()` function and the available built-in names, Craftr should feel like rather natural Python. The built-ins are a convenience to keep scripts short, without having to explicitly import a lot of stuff that is used frequently (path manipulation in particular).

Thanks for your feedback!

**Comment by tliron** [comment]
Thanks for the clarification, I will be keeping track of progress on Craftr 2. I would love if you gave Rōnin a try and also gave me feedback! There are quite a few examples included that can give you a quick idea of how it is structured.
