### ISSUE TITLE
Add support for CFLAGS, CPPFLAGS, LDFLAGS, etc. in Craftr 2.x

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#152]
This feature is currently disabled in Craftr 2.x because there is currently no option to specify `buildtype=external` as it was possible in Craftr 1.

**Comment by SadE54** [comment]
yeah seriously needed :)

**Comment by SadE54** [comment]
I saw in the commit : "flags = shell.split(os.getenv('LDFLAGS', '').strip())"
So we can only give linker flags by os vars ?

**Comment by NiklasRosenstein** [comment]
Currently, yes. Do you think that is too limiting? I could add options that can be specified like `-d "ldflags=<flags here>"`

**Comment by SadE54** [comment]
Yeah please, for compiler used for embedded you always hava a lot of
options for the linker , like the scatter file , ...
Thanks !



2017-01-15 6:59 GMT+01:00 Niklas Rosenstein <notifications@github.com>:

**Comment by NiklasRosenstein** [comment]
Ok, I'll add that. Just in case you didn;t know, you can also specify additional linker flags in the Craftrfile.

```python
cxx = load('craftr.lang.cxx')
main = cxx.executable(  # recently renamed from binary(), backwards compatible name still available
  output = 'main',
  input = ... ,
  additional_flags = ['cross', 'platform', 'linker', 'flags'],
  llvm_additional_flags = ['flags', 'only', 'for', 'llvm'],
  gcc_additional_flags = ['flags', 'only', 'for', 'gcc'],
  msvc_additional_flags = ['flags', 'only', 'for', 'msvc']
)
```
