### ISSUE TITLE
cython_project and gcc flags

### ISSUE THREAD

**Issue by dfroger** [craftr-build/craftr#153]
In craftr 2.x, using`cython_project`, it is easy to set `Cython` flags (which compiles `.pyx` into `.c`).

But how can I set `gcc` flags (which compiles `.c` generated by Cython)?

Thanks!

**Comment by NiklasRosenstein** [comment]
Hey, sorry for the late reply! I guess  #152 would do the job, but I agree that there should also be an optional explicitly pass additional flags to the compilation units created by `cython_project()`. Will add it in a bit :)

**Comment by dfroger** [comment]
Hi, it works nice, thanks! I've used it this [Craftrfile](https://github.com/dfroger/quickstart/blob/824c4cbff86516461e3790d3c7c28c20a3bc3194/cython/exception/src/Craftrfile#L21) ([doc](https://github.com/dfroger/quickstart/tree/master/cython/exception)).

**Comment by NiklasRosenstein** [comment]
You can use 

```cpp
  compile_kwargs = dict(
      include = [cysignals_include]
  )
```

instead of

```cpp
  compile_kwargs = dict(
      gcc_compile_additional_flags = ['-I' + cysignals_include]
  )
```

:)
