### ISSUE TITLE
broken (?) implicit_deps expansion

### ISSUE THREAD

**Issue by mcquay239** [craftr-build/craftr#173]
Hi Niklas! Thank you for craftr :)

There is a strange genalias behavior: I generated several _explicit_ targets with aliases and created an implicit _all_ alias for them like

```
explicit_1 = generate(..., name="alias_1", explicit=True)
explicit_2 = generate(..., name="alias_2", explicit=True)
...
all = genalias(explicit_1, explicit_2, ..., name="all")
```

You don't generate phony rules for explicit targets and the _all_ target becomes inconsistent. I worked around it with something like

```
all = genalias(*(explicit_1.outputs + explicit_2.outputs + ...), name="all")
```

But maybe the right way is to switch the mode in expanding mixed list (core/build.py:276)?

**Comment by NiklasRosenstein** [comment]
Closing as irrelevant for Craftr 4.
