### ISSUE TITLE
Add objcopy() rule to compiler modules

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#20]
A rule `objcopy()` to invoke the GNU `objcopy` tool should be added.

**Comment by NiklasRosenstein** [comment]
I'm thinking about delaying this when there would be a higher demand and the need to provide an abstract interface to the `objcopy` tool. For now, it can easily be written with a standard `target()` definition.

```python
testbin = target(
  inputs = testelf,
  outputs = [join(project_dir, 'test.bin')],
  command = ['objcopy', '-O', 'binary', '%%in'],
)
```

**Comment by winksaville** [comment]
SG

**Comment by NiklasRosenstein** [comment]
With Craftr 0.20.0-dev, this target would look like this instead:

```python
testbin = Target(
  command = 'objcopy -O binary $in',
  inputs = teself,
  outputs = [path.local('test.bin')],
)
```

**Comment by winksaville** [comment]
I'd sure like to be able to create an ObjCopy translator with the command
specified and then use the ObjCopy translator with various inputs and
outputs.

**Comment by NiklasRosenstein** [comment]
Ok, I've added an `Objcopy` class to the `unix` extension module, see 91c6d7b. You would use it like this:

```python
from craftr.ext import unix
objcopy = unix.Objcopy(program='arm-eabi-objcopy')
testbin = objcopy.objcopy(
  inputs = testelf,
  output_format = 'binary',
)
```

Note that this is very experimental as I don't really have something to test this here. By default, the class will call `objcopy --help` and use regex to find the supported targets. If you choose an `output_format` or `input_format` that was not in that list of supported targets, there'll be an error.

**Comment by winksaville** [comment]
You can fork my project, but I'll give it ago sometime soon.

**Comment by NiklasRosenstein** [comment]
I'd have a to build a cross-compiler first, no? :)

**Comment by NiklasRosenstein** [comment]
Ah I mess up the two issues. :) https://github.com/craftr-build/craftr/issues/3#issuecomment-163739727

**Comment by winksaville** [comment]
I've created a project to make it "easy", you're welcome to give it a try.
