### ISSUE TITLE
Refactoring of compiler modules

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#22]
The compiler modules are currently based on `compiler.base.BaseCompiler` which implements the `objects()`, `executable()`, etc. rule functions and they use the `command()` function which must be implemented by subclasses of `BaseCompiler`. The design is very flawed and makes it hard to maintain the code and it is not elegant at all.

There should be a base class, maybe called `Translator` or `CommandBuilder` that implements and interface that fullfills the following constraints:

1. Easy to implement the generation of build commands based on options
2. Options should be definable on an object-level and call-level (options defined on call-level should override object-level options)
3. Options should be able to have more influence than just on the build command (eg. an option `autodeps` could append `-MMD -MF %%out.d` to the build command but as well add a meta variable `depfile` to the result of the call that specifies `%%out.d`. The caller would know that this meta variable might be set and can use it accordingly)
4. More might be following..

> Note: There is already a `craftr.utils.CommandBuilder` atm. but it isn't really what I am looking for either. It will be removed with the resolving of this issue.

----

An early draft of a `Translator` subclass:

```python
class CCompiler(Translator):

  def _handle_autodeps(self, autodeps=True, depsfile='%%out.d'):
    if autodeps:
      self.result.meta['depsfile'] = depsfile
      self.result.command.extend(['-MMD', '-MF', depsfile])

  def _handle_includes(self, includes):
    self.result.meta.setdefault('includes', []).extend(includes)
    self.result.command.extend(['-I{}'.format(x) for x in includes])

  def _handle_defines(self, defines):
    self.result.meta.setdefault('defines', []).extend(defines)
    self.result.command.extend(['-D{}'.format(x) for x in defines])
```

All functions that start with `_handle` would be called for the options passed to `Translator.translate(**options)`. In order to be able to accept only the necessary arguments, introspection would be applied to figure out the accepted argument names and call those functions that accept an argument of an option. A `_handle...()` function would be invoked even if only one of its arguments are defined in the options. The `Translator.result` would be set to a `TranslatorResult` instance during the runtime of a `Translator.translate()` call.

**Comment by NiklasRosenstein** [comment]
As it is now, it is not _very_ different from before, but the `Translator` class has some features that make it more appealing. The `Translator.Result` has the members `program`, `command`, `meta` and `requires`. The former two should be obvious. `meta` is for any kind of data that might be known to be available after `Translator.translate()` had been called. `requires` can list any filenames that should be listed as "requirement input files" for a target (ie. a changed file will trigger a rebuild, but it is not considered a direct input file as it will not expand with `%%in`).

Here's an example on the new [java](https://github.com/craftr-build/craftr/blob/dfc1880a0dfdb0bc1db5fa2bd3e4723ed39466cb/craftr/builtins/java.craftr) module.

**Comment by winksaville** [comment]
Interesting notion of iterrating over the handlers passing the options. Are
the kwargs passed to a handler "consumed" as a handler "uses" it, I doesn't
look like it and maybe it shouldn't, just wondering?

Coming from C++/Java I probably would have just put the key/value pairs in
a dictionary and have the child class override the abstract translate
method and do whatever is necessary. Nothing against what you've done just
idle observation.

One other missing piece of craft is the need for a test infrastructure. I'd
like to suggest adding it soon as it can make up for the lack of
documentation in the short term:)

**Comment by NiklasRosenstein** [comment]
I'm not following this `_handle...()` and `Translator` route in craftr 0.20.0-dev. The generic C/C++ interface will look like this:

```python
# craftr_module(nr.test)

from craftr import path
from craftr.ext.compiler import get_platform_toolset

tools = get_platform_toolset()
cc = tools.CCompiler()
ld = tools.Linker()

objects = cc.compile(
  sources = path.glob('src/*.c'),
)

main = ld.link(
  inputs = objects,
  output = 'main',
  output_type = 'bin',
)
```

> One other missing piece of craft is the need for a test infrastructure. I'd
like to suggest adding it soon as it can make up for the lack of
documentation in the short term:)

@winksaville  Do you mean a testing infrastructure for Craftr itself, or to be able to run tests for projects compiled with Craftr?

**Comment by winksaville** [comment]
You said "I'm not following" did you mean "I'm now following"?

**Comment by NiklasRosenstein** [comment]
> You said "I'm not following" did you mean "I'm now following"?

Not a typo. I'm sticking with classic command line argument generation [like this](https://github.com/craftr-build/craftr/blob/fc1ab8a1ee49221f78e0bd81327dabef2d9cb34d/craftr/lib/compiler.msvc.craftr#L96-L156).

**Comment by NiklasRosenstein** [comment]
I think this issue can be closed. The compiler modules are working well and I'm kinda satisfied with the design for now. Of course, there is much room for improvement such as implementing additional options or optimized default behaviour etc. but that is not in the scope of this issue.
