### ISSUE TITLE
Add build subcommand to merge export and ninja step

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#23]
Currently, there are two ways to build a project. You can derive the output build directory from code, but that can sometimes be rather complicated depending on your needs and dependent modules might not take this build directory into account.

The preferred way now is to use the current working directory as the build output directory, but each module should use a folder that is named after its module name (so that no conflicts in eg. object files can occur between modules).

You usually don't want to mess up your working tree with the stuff, so you instead create a build directory inside it and run craftr from there.

    mkdir build && cd build
    craftr -c .. export && ninja

A convenient subcommand should be added to merge these steps and that can be called from the working directory rather than the build directory.

    craftr build

There should be options to specifiy the build directory name, and whether the ninja build file should be exported even if it already exists.

**Comment by winksaville** [comment]
NICE, one question can the build directory be outside. i.e. will these work:
```
craftr ../build-versatilepb
craftr ../build-posix
```

**Comment by NiklasRosenstein** [comment]
Yes, that will work with no further ado. :smile:

**Comment by winksaville** [comment]
Cool, I'll give it a try. I'm glad to see you've found some time for Craftr.
