### ISSUE TITLE
Extended compiler support for GCC, Clang and MSVC

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#3]
- [x] Support for compiler optimization levels (speed, space, debug)
- [x] ASM compiler interface for GCC, Clang and MSVC
- [x] MSVC support for platform toolset versions
- [x] Auto dependency support (see also #2)
- [x] Support for cross-compilers
- [x] Automated compiler detection via `CC`, `CXX` and `LD` environment variables

**Comment by NiklasRosenstein** [comment]
Working on a Common Compiler Interface specification: https://github.com/craftr-build/craftr/wiki/Common-Compiler-Interface

**Comment by winksaville** [comment]
A few thoughts:

As much as possible it needs to model the parameters/features abstractly
and then convert the abstract concept to concrete parameters. As an example
optimization parameters maybe speed, space, debug. Which for gcc an clang
would be -Ox but on MS compilers they maybe different.

The compiler modules should also be able to automatically use compiler
dependency determination or if it's not supported the the compiler module
needs to provide a suitable equivalent or warn the user of potential
problems.

Also it's important to handle dependency upon generated code  generation
such as lex, yacc, protobuf ...

**Comment by NiklasRosenstein** [comment]
Thanks for your input, Wink! Could you elaborate on lex, yacc and protobuf? I've never used any of these.

**Comment by NiklasRosenstein** [comment]
Also, you mentioned cross compilers. How do you use them (or would prefer to use them)? Do you set the `CC`, `CXX` etc. environment variables or do you use the absolute path to the compiler?

**Comment by winksaville** [comment]
lex, yacc and protobuf are "compilers" which generate "C" code which then
needs to be compiled.

Cross-compilers are compilers which generate code for systems other than
the system doing the actual compilation. Meson just added support for Candian
Cross Compiling
<https://en.wikipedia.org/wiki/Cross_compiler#Canadian_Cross>, although I
haven't been able to make to do "bare metal" cross compiling yet. I did get
CMake to work on my baremetal-hi
<https://github.com/winksaville/baremetal-hi> app, but it was painful.

Pedantic description of Bare Metal programming (*ignore if you know what it
is :)* is where you're writing code directly against the hardware, such as
an for a deeply embedded system or writing an OS, such as the linux kernel.

In these situations the author needs to also control the linker in gcc this
is using a linker script. In baremetal-hi
<https://github.com/winksaville/baremetal-hi> the linker script is:

[wink@wink-envy baremetal-hi]$ cat link.ld
ENTRY(_Reset)
SECTIONS
{
  . = 0x10000;
  .startup  . : { startup.o(.text) }
  .text : { *(.text) }
  .data : { *(.data) }
  .bss : { *(.bss COMMON) }
  . = ALIGN(8);
  . = . + 0x1000; /* 4kB stack */
  stack_top = .;
}

**Comment by NiklasRosenstein** [comment]
@winksaville  There's basic support for lex, yacc and protobuf in craftr 0.20.0-dev! Example for protobuf:

```python
from craftr import path
from craftr.ext.compiler.protoc import ProtoCompiler

protoc = ProtoCompiler()

proto_sources = protoc.compile(
  sources = path.glob('src/messages/*.proto'),
  proto_path = path.local('src/messages'),
  cpp_out = 'proto',  # "proto" folder in the build directory
)

# pass proto_sources as inputs to a compiler or use proto_sources.outputs to get
# a list of the output .cc files. proto_sources.meta['includes'] contains a list of
# additional include directories to include the proto message headers.
```

Regarding linker scripts, I'll add support when I implement the compiler classes for GCC/Clang for craftr 0.20.0-dev.

**Comment by NiklasRosenstein** [comment]
Btw. for cross compiling, is there anything necessary beyond being able to manually specify the actual compiler program that is being used to compile?

**Comment by NiklasRosenstein** [comment]
@winksaville Also, looking at your [Craftfile](https://github.com/winksaville/baremetal-hi/blob/master/Craftfile) in baremetal-hi, it looks like you're specifying the command-line arguments almost completely manually, anyway. There's not much need for abstraction if you only target a specific compiler, is there?

This script should do the same in craftr 0.20.0-dev, without compiler abstraction.

```python
# craftr_module(baremetal_hi)

from craftr import path, platform, expand_inputs, Target
from craftr.ext.compiler import gen_objects
from functools import partial

mkobj = partial(gen_objects, suffix=platform.obj)

test_object = Target(
  command = 'arm-eabi-gcc $in -o $out -DBmArm -mcpu=arm926ej-s',
  inputs  = [path.local('test.c')],
  outputs = mkobj,
)

startup_object = Target(
  command = 'arm-eabi-gcc $in -o $out -DBmArm -DRESET_ON_MAIN_COMPLETE -mcpu=arm926ej-s',
  inputs  = [path.local('startup.S')],
  outputs = mkobj,
)

testelf = Target(
  command = 'arm-eabi-ld $in -o $out -T "{0}"'.format(path.local('link.craftr.ld')),
  inputs  = [startup_object, test_object],
  outputs = 'test.elf',
)

testbin = Target(
  command = 'arm-eabi-objcopy -O binary $in $out',
  inputs  = testelf,
  outputs = 'test.bin',
)

run = Target(
  command = 'qemu-system-arm -M versatilepb -m 128M -nographic -no-reboot -kernel $in',
  inputs  = testbin,
  pool = 'console',
)
```

**Comment by winksaville** [comment]
I'd rather work at a higher level then Target, it seems to me I should be
able to create "Compiler", "Archiver", "Linker" with default "commands" and
"flags" then use those Entities with other input and output parameters to
compile/archive/link new objects. It looks to me I'd have to respecify all
of the commands for every translation I want to do.

**Comment by NiklasRosenstein** [comment]
Ok, I've added an `Objcopy` class to the `unix` extension module, see 91c6d7b. You would use it like this:

```python
from craftr.ext import unix
objcopy = unix.Objcopy()
testbin = objcopy.objcopy(
  inputs = testelf,
  output_format = 'binary',
)
```

Note that this is very experimental as I don't really have something to test this here. By default, the class will call `objcopy --help` and use regex to find the supported targets. If you choose an `output_format` or `input_format` that was not in that list of supported targets, there'll be an error.

**Comment by NiklasRosenstein** [comment]
> I'd rather work at a higher level then Target, it seems to me I should be
able to create "Compiler", "Archiver", "Linker" with default "commands" and
"flags" then use those Entities with other input and output parameters to
compile/archive/link new objects. It looks to me I'd have to respecify all
of the commands for every translation I want to do.

The thing is that what you are doing seems to be coupled with the actual
tools used. What would be possible is to use an OOP interface, without
hardcoding the commands, but not derive the tools from the environment and
instead import them directly.

```python
from craftr import path, Target
from craftr.ext.compiler.gcc import GccCompiler
from craftr.ext.unix import Ld, Objcopy

gcc = GccCompiler(
  program='arm-eabi-gcc',
  defines=['-DBmArm'],
  additional_flags=['-mcpu=arm926ej-s']
)

objcopy = Objcopy(program='arm-eabi-objcopy')
ld = Ld(program='arm-eabi-ld')                                    

# Targets

test_object = gcc.compile(
  sources = [path.local('test.c')],
)

startup_object = gcc.compile(
  sources = [path.local('startup.S'),
  defines = ['RESET_ON_MAIN_COMPLETE'],
  language = 'asm',
)

testelf = ld.link(
  inputs = [test_object, startup_object],
  outpust = [path.local('test.elf')],
  linker_script = path.local('link.craftr.ld'),
)

testbin = objcopy.objcopy(
  inputs = testelf,
  output_format = 'binary',
)

run = Target(
  command = ['qemu-system-arm', '-M', 'versatilepb', '-m', '128M', '-no-reboot', '-kernel', '$in'],
  inputs  = testbin,
  pool = 'console',
)
```

**Comment by winksaville** [comment]
This looks exactly what I like. Regarding ObjCopy, txs for creating that,
but it was more an example. I suspect there are many "custom" Translators
and it would be nice to create them in a Craftrfile rather than having to
modify the Craftr source. I realize there would be limitations but I'd
guess that something as simple as objcopy should be doable. Of course I
could be totally wrong :)

**Comment by NiklasRosenstein** [comment]
Well, of course you could've put the code I put in `compiler.unix.craftr` into your Craftfile instead. :)

**Comment by NiklasRosenstein** [comment]
@winksaville  I've update the Craftfile above](https://github.com/craftr-build/craftr/issues/3#issuecomment-163703266). You can run `craftr -eb` to run it with `arm-eabi-` as compiler prefix or, what I do, `craftr-eb -Dcprefix=''` to omit the `arm-eabi-` prefix.

I get

```
[2/4] gcc -x c -c /home/niklas/Desktop/baremetal-hi/test.c -o /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/test.o -DBmArm -mcpu=arm926ej-s
FAILED: gcc -x c -c /home/niklas/Desktop/baremetal-hi/test.c -o /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/test.o -DBmArm -mcpu=arm926ej-s
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
/home/niklas/Desktop/baremetal-hi/test.c:1:0: error: bad value (arm926ej-s) for -mtune= switch
 typedef unsigned char uint8_t;
 ^
[2/4] gcc -x c -c /home/niklas/Desktop/baremetal-hi/startup.S -o /home/niklas/De...ild/baremetal_hi/obj/startup.o -DRESET_ON_MAIN_COMPLETE -DBmArm -mcpu=arm926ej-s
FAILED: gcc -x c -c /home/niklas/Desktop/baremetal-hi/startup.S -o /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/startup.o -DRESET_ON_MAIN_COMPLETE -DBmArm -mcpu=arm926ej-s
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
/home/niklas/Desktop/baremetal-hi/startup.S:1:0: error: bad value (arm926ej-s) for -mtune= switch
   .global _Reset
 ^
ninja: build stopped: subcommand failed.
```

Does this have to do with the fact that it's not a cross compiler? :-)

**Comment by winksaville** [comment]
Yes you need a cross compiler see this
<https://github.com/winksaville/vendor-install-tools>. But it looks like
Craftr didn't use your "arm-eabi-" because I would have expeced the "gcc"
commands to be "arm-eabi-gcc".

**Comment by NiklasRosenstein** [comment]
@winksaville As I mentioned in the previous comment, I don't have `arm-eabi-gcc` that is why I tried it with `gcc` instead :D Thanks for the link, I'll try that when I find time for it.

**Comment by winksaville** [comment]
Its early/late for you, you need to get some sleep :)

**Comment by NiklasRosenstein** [comment]
@winksaville Did you see that I forked (and reworked) your [vendor-install-tools](https://github.com/NiklasRosenstein/vendor-install-tools)?

I could get them installed now and I'm trying to compile baremetal-hi. Unfortunately I can't find out where this `crt0.o` error comes from? I've tried it with and without `-nostdlib -nostartfiles -ffreestanding`. Could you help me with this?

```
niklas@sunbird:~/Desktop/baremetal-hi$ craftr -eb -N -v
[1/4] arm-eabi-gcc -c /home/niklas/Desktop/baremetal-hi/startup.S -o /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/startup.o -DRESET_ON_MAIN_COMPLETE -DBmArm -Wall -O0 -MD -MP -MF /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/startup.o.d -mcpu=arm926ej-s -nostdlib -nostartfiles -ffreestanding
[2/4] arm-eabi-gcc -x c -c /home/niklas/Desktop/baremetal-hi/test.c -o /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/test.o -DBmArm -Wall -O0 -MD -MP -MF /home/niklas/Desktop/baremetal-hi/build/baremetal_hi/obj/test.o.d -mcpu=arm926ej-s -nostdlib -nostartfiles -ffreestanding
[3/4] arm-eabi-gcc  -Wl,-T,baremetal_hi/link.ld -o /home/niklas/Desktop/baremetal-hi/build/test.elf
FAILED: arm-eabi-gcc  -Wl,-T,baremetal_hi/link.ld -o /home/niklas/Desktop/baremetal-hi/build/test.elf
/home/niklas/opt/lib/gcc/arm-eabi/5.2.0/../../../../arm-eabi/bin/ld: cannot find crt0.o: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by winksaville** [comment]
No I didn't see that, but it looks like you need to merge your changes with
the my latest changes. I'm now using crosstool-ng to generate the arm, i386
and x86_64 compilers. I couldn't get my x86_64 compiler to work so using
crosstool-ng seemed the easiest solution rather than beating my head
against the wall to figure out the right switches.

As for your problem I think you need -nodefaultlibs  too, give my latest
vendor-install-tools you can try baremetal-x86_64
<https://github.com/winksaville/baremetal-x86_64> also. I've haven't yet
tried to update baremetal-hi, but lets update it after we get
vendor-install-tools working.

-- Wink

**Comment by NiklasRosenstein** [comment]
Trying to install `crosstool-ng`, but I get

```
checking for GNU libtool >= 1.5.26... no
configure: error: could not find GNU libtool >= 1.5.26
```

Although I did `sudo apt-get install libtool`

**Comment by winksaville** [comment]
Hmm, look at the circle.yml file for the things I needed to install for
Ubuntu 12.04. Might try rebooting or maybe your PATH isn't right.

Everything is always harder that it should be :(

**Comment by NiklasRosenstein** [comment]
I'll mark "Support for cross-compilers" as completed as it's just a matter of specifying the compiler via the `CC` variable.
