### ISSUE TITLE
Support for Craftr environment files

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#35]
Craftr is usually configured with the environment, just like most other build tools. The `-Dkey=value` option also just appends to the process' environment. There might be cases where you want a single project or all projects you build to be configured with a specific environment always. Also, if your project requires platform dependent configuration, users should not need to modify the `Craftfile` but instead add or modify the Craftr environment file.

I want to add support for a file that is also plain Python but loaded before any other modules. This file will be loaded from the current working directory of Craftr and from the user home directory. I would call it `Craftenv` or `.craftenv` or something like that. It could look like this:

```python
from os import environ
environ['MYO_SDK_PATH'] = '/absolute/path/to/myo/sdk'
environ['CROSS_COMPILER_PREFIX'] = 'arm-eabi-'
# etc.
```

**Comment by winksaville** [comment]
Having the Craftenv/.craftenv is a good idea. Meson has a "environment" concept its called meson_options.txt, but AFAICT it must always be called that. I'd like to suggest you also provide a command line option so we can specify the "Craftenv" file on the command line.

Allowing the plain Python should allow the programmer to enhance Craftr without changing Craftr, correct?

**Comment by NiklasRosenstein** [comment]
> Allowing the plain Python should allow the programmer to enhance Craftr without changing Craftr, correct?
Yes, it would allow you to hook into Craftr before any Craftfiles are executed. You can do whatever you like, eg. monkeypatching functions or changing environment variables.

Good idea, I will also add an option to specify an environment file via the command-line and also an option to disable the loading of the default environment files (from `~/Craftenv` and `./Craftenv`).

**Comment by NiklasRosenstein** [comment]
Hm, not quite right. It needs some extra work.

```python
from os import environ
from craftr import path
environ['MYO_SDK_PATH'] = path.local('../myo-sdk-win-0.9.0')
environ['MYO_SDK_WINARCH'] = '32'
```

Results in 

```
  File "C:\Users\niklas\repos\NiklasRosenstein\myo-python\thalmic.myo\Craftenv", line 3, in <module>
    environ['MYO_SDK_PATH'] = path.local('../myo-sdk-win-0.9.0')
  File "c:\users\niklas\repos\craftr-build\craftr\craftr\path.py", line 257, in local
    return normpath(path, module.project_dir)
  File "F:\Python34\lib\site-packages\werkzeug\local.py", line 342, in __getattr__
    return getattr(self._get_current_object(), name)
  File "F:\Python34\lib\site-packages\werkzeug\local.py", line 301, in _get_current_object
    return self.__local()
  File "c:\users\niklas\repos\craftr-build\craftr\craftr\magic.py", line 45, in _lookup
    raise RuntimeError('outside of {0!r} context'.format(context_name))
RuntimeError: outside of 'module' context
```

Because `Session.exec_if_exists()` does not enter a module context. It should emulate that and create a temporary fake module object to enter the `module` context with.

**Comment by NiklasRosenstein** [comment]
@winksaville Does that match your taste? `Craftenv`

```python
# -*- mode: python -*-

from os import environ
from craftr import path, platform

# Set up some default environment variables.
if 'MYO_SDK_PATH' not in environ:
  sdk_path = path.local('../myo-sdk-{0}-0.9.0'.format(platform.ident))
  print('Setting up default MYO_SDK_PATH =', sdk_path)
  environ['MYO_SDK_PATH'] = sdk_path

if platform.name == 'Windows' and 'MYO_SDK_WINARCH' not in environ:
  arch = environ.get('architecture', '32')
  print('Setting up default MYO_SDK_WINARCH =', arch)
  environ['MYO_SDK_WINARCH'] = arch
```

This is some kind of "bootstrap" code that is executed before the `Craftfile` to make sure some environment variables are initialized with default values. If you check the [`thalmic.myo`](https://github.com/craftr-build/thalmic.myo/blob/master/Craftfile) source, it reads the environment variable and defines the framework parameters accordingly.

**Comment by winksaville** [comment]
LGTM!
