### ISSUE TITLE
Add option to exclude a Target from the default build

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#37]
Craftr generates a `default <target> [<target> [...]]` declaration at the end of a ninja build file. There should be an option exclude a target from this declaration, so it will only be built if another target depends on it or if it is explicitly targeted when calling `craftr -b <target>` or `ninja <target>`.

**Comment by winksaville** [comment]
YES!!!

**Comment by NiklasRosenstein** [comment]
Note that since Craftr 0.20.0, Targets in the `"console"` pool have never been added to that `default` statement in ninja. Now that the `Target.explicit` attribute was added, it can be used to exclude the target without setting the pool to `"console"`

**Comment by winksaville** [comment]
I ran into a problem with "console" when I was using CMake, so this sounds
good.
