### ISSUE TITLE
Split targets and build rules, like Ninja does

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#38]
If you're declaring the same target with the same command over and over again, you will have the command duplicated every time in a new rule. We should split a `Target` into `Rule` and `Build`, just like Ninja does it. The compiler interface could look like this instead.

``` python
objects = compiler.toolset.CxxCompiler().objects(include=[...], etc..)
objects.build(path.glob('src/*.cpp'))
```

**Comment by winksaville** [comment]
LG, keeping the granularity small and building on those is a good idea,
then others can combine them in different ways, but the high level
interface can still remain "easy" to use!

**Comment by NiklasRosenstein** [comment]
It's a bit of scope for now. Maybe at a later point in the development.

**Comment by NiklasRosenstein** [comment]
I have been trying to approach this, however it would introduce a lot of complexity. I think for the time being I won't implement this.
