### ISSUE TITLE
Move compiler.toolset to platform.toolset

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#39]
Makes more sense. :-)

**Comment by winksaville** [comment]
I'm curious, can multiple tool sets be used in a given build, so could I
use gcc and clang at the same time on different "Compiler's"?

**Comment by NiklasRosenstein** [comment]
Using Clang and GCC at the same time is no problem at all. Only the platform toolset won't give you both of them at the same time.

```python
from craftr.ext.compiler import gcc, llvm

gcc_cxx = gcc.CxxCompiler()
llvm_cxx = llvm.CxxCompiler()

gcc_objects = gcc_cxx.compile(
  sources = path.glob('src/*.cpp')
)

llvm_objects = llvm_cxx.compile(
  sources = path.glon('src/*.cpp'),
)
```

**Comment by winksaville** [comment]
SG, so a single platform defines a particular toolset can I, the user of
Craftr, create different platforms?

**Comment by NiklasRosenstein** [comment]
Depends on what *you* think of as a platform in this context. The `craftr.ext.platform` module simply checks the OS name and does some very simple definitions based on that. [Goto platform.craftr](https://github.com/craftr-build/craftr/blob/master/craftr/lib/platform.craftr)

In some previous version, Craftr used to have separate modules for the supported platforms, eg `platform.nt`, `platform.linux`, `platform.darwin` and the `platform` module basically did the same as it does now, only import the definitions from these sub-modules.

It might be useful to add that again in case you need access to other platform definitions rather than the current one.

```python
from craftr.ext.platform import linux
cc = linux.toolset.CCompiler()  # that probably doesn't make sense
linux_objects = linux.obj(path.glob('src/*.c'))  # that probably does a lot more sense
```

**Comment by winksaville** [comment]
I'm not sure, I just hope that there are "defaults" based on the current
platform but that any default can be "trivially" overridden. This is just a
restatement of my desire to be able to control the defaults and be able to
use cross-compilers, or gcc or clang or gold linker or ld linker or .....

I definitely want easy things to be easy and there should be "platform"
defaults but I, the programmer, should be able to changes these defaults.
And also be able to use multiple tools that overlap in functionality and
sometimes use tool A and sometimes tool B. (I sound like a broken record :)
)

I think you're really close!

-- Wink
