### ISSUE TITLE
Use of LD variable to determine the linker

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#48]
As far as I know, you usually use `gcc`/`g++` instead of `ld` to link C object files into an executable or shared library as it does the job of invoking the linker for you. Craftr does currently not take the `LD` variable into account and just uses whatever C compiler is configured as the linker.

**Comment by winksaville** [comment]
At a minimum you need to be able to pass linker specific options with the
gcc "-Wl" option such as I use in this Makefile
<https://github.com/winksaville/baremetal-x86_64/blob/master/Makefile> on
lines 44 and 48.

**Comment by NiklasRosenstein** [comment]
I've added a `linker_args`/`gcc_linker_args`/`llvm_linker_args` and `linker_script`option to the GCC/LLVM compilers' `.link()` function.

**Comment by winksaville** [comment]
Cool

**Comment by NiklasRosenstein** [comment]
Linking on Unix shall always happen through the C/C++ compiler. If someone really wants to invoke `ld` manually, he can use `craftr.ext.unix.Ld`.
