### ISSUE TITLE
Command-line too long

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#67]
Not sure about linux, but Windows has a hard cap on the length of a command-line. Windows commands like `cl` and `link` support a `@filename` syntax from which they'll read the arguments.

**Comment by NiklasRosenstein** [comment]
Steps to resolve this problem:

1. The `Session` class should get a `export` attribute that is set when the `-e` option is passed
2. Rules can then check `session.export` and eventually export a commands file that is then passed via the command-line instead. These files should be put into a `.cmd` folder in the build directory and saved under the full-spec target name.

A Windows link command could then look like this: `link @.cmd/nr.projection_lens.plugin`. Ideally, this would only happen when really necessary and otherwise pass the arguments traditionally on the command-line.

**Comment by NiklasRosenstein** [comment]
This is a bit more problematic than I initially thought since the command-line contains the Ninja variables `$in` and `$out` and checking if the command-line would be too long is not an obvious task. Eventually, commands that support `@file` syntax should always use it.

**Comment by NiklasRosenstein** [comment]
It seems like this issue is only present when prefixing a command with `cmd /c`! Unfortunately in some cases, we have to run it through `cmd /c` as some programs are not found otherwise. Gotta investigate what these cases are.

**Comment by winksaville** [comment]
Some systems shouldn't be used for development :)

**Comment by NiklasRosenstein** [comment]
I'm bound to using Windows for work unfortunately. ;-)

So it seems like the Win32 API `CreateProcess()` function "can only be used with executable images". <sup>[[reference]](http://stackoverflow.com/questions/34578247/ninja-batch-file-as-command#comment56901670_34578247)</sup>

**Comment by NiklasRosenstein** [comment]
Ok so on Windows I'll just try to find the program that is being executed, check if it is an executable image, and if it is not, run it via `cmd /c`.
