### ISSUE TITLE
Add option to change the main project directory

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#68]
Currently, Craftr uses the current working directory and the original main project directory and then immediately switches to the build directory. This new option should change that original project directory. If the `-d` option (build directory) is not specified, the *current directory* should be used as the build directory. Use either `-p` for "project directory" or `-c` for "craftfile directory" for the new option.

**Comment by NiklasRosenstein** [comment]
`-c` is already used for clean. Gonna be `-p`

**Comment by winksaville** [comment]
SG, txs!
