### ISSUE TITLE
add debug() log function

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#69]
It should only display output with a verbosity level >= 1.

**Comment by winksaville** [comment]
I know documentation is hard, but if you can create simple tests with
descriptive names pertaining to a the feature then I can discover how to
use features such as this and others. You may already have done this, my
apologies if so, I'm away from my computer.

**Comment by winksaville** [comment]
Whoops, I lost my thank you, this is a feature sorely missing form meson :)

**Comment by NiklasRosenstein** [comment]
I've added some information about the API here: https://github.com/craftr-build/craftr/wiki/API

**Comment by winksaville** [comment]
Nice, txs!
