### ISSUE TITLE
Address relative targets with starting dot

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#72]
On the command-line, to indicate that a target name or variable name is relative to the current main module, it should be prefixed with a dot, like `.main`.

**Comment by winksaville** [comment]
Hmmm, when using ninja with baremetal-hi I've got to prefix the targets
with 'baremetal_hi' so the run target is baremetal_hi.run. Does this mean
it will be .run ?

**Comment by NiklasRosenstein** [comment]
No this won't have any effect on the way you call ninja directly.
