### ISSUE TITLE
Introduce target metadata

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#82]
Imagine you have a rule that creates a target to create a static library from object files. This target does not only yield one file (the library), but maybe an additional file (for example a file that contains metadata, a list of exported symbols or whatever). Now you have no *good* way of reading the actual filename of the library. You *could* assume it's the first element of `Target.outputs`, but who's going to guarantee that?

The `Target.meta` attribute should be a dictionary that can be filled by the rule function. For example, it could add a key `staticlib_output` to that dictionary that contains the actual filename of the library that is produced by the target.

```python
lib = ar.staticlib(
  output = 'foo',
  inputs = objects
)
info('Static Lib will be produced at:', lib.meta['staticlib_output'])
```

The existing compiler interface should implement this respectively.

* `staticlib_output` for `ar.staticlib()`
* `link_output` for `link.link()`

**Comment by winksaville** [comment]
How about adding a user_meta so the user can add meta data they may need:

  lib = ar.staticlib(
   output = 'foo',
   inputs = objects
   user_meta = [ 'addr' : '0x12346' ])

  info('Static Lib will be produced at:',
         lib.meta['staticlib_output'])

  info('Static Lib addr:', lib.user_meta['addr'])

**Comment by NiklasRosenstein** [comment]
Yes that would be useful. I'd go as far as to merge them into the same dictionary. The target metadata should only be used when necessary and not be filled up with crap. The values that the rule functions write into that dictionary should be clearly defined to avoid overwrites from the user or reverse.

**Comment by winksaville** [comment]
Nice!
