### ISSUE TITLE
More intuitive command-line interface

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#91]
Craftr is currently purely based on command-line switches like `-e`, `-b` and `-cc`. While it is quite nice to be able to do all in a single command (clean, export new manifest, build), the flags only interface is not very intuitive and doesn't scale with future plans (see #90 for example).

A new interface could look like this

* `craftr export` &ndash; New command for `craftr -e`
* `craftr build` &ndash; New command for `craftr -b`
* `craftr clean [TARGET [...]]` &ndash; New command for `craftr -cc` and `craftr -c [TARGET [...]]`
* `craftr rts start` &ndash; New command for `craftr --rts`
* `craftr rts invoke` &ndash; New command for `craftr-rts-invoke`
* `craftr run COMMAND` &ndash; New command for `craftr -F COMMAND`

_Eventually_ I will take into consideration to preserve the old flag-style invocation to still be able to combine multiple tasks into one command.

**Comment by NiklasRosenstein** [comment]
Hm, after some thinking, I kind of like that I can invoke multiple actions with one command-line (eg. export and build). However, what I would really like to see is that you can treat functions (tasks) the same as build targets on the command-line.

Currently, you can only run a pre-build task and a post-build task with `-f [task]` and `-F [task]` respectively. I would like to invoke a craftr build like this:

    craftr -e task1 target1 task2 target2 target3 task3

First, Craftr would run `task1`, then invoke Ninja to build `target1`, then again Craftr runs `task2` then invoke Ninja for `target2 target3`, then Craftr runs `task3`. The `-e` switch would still do the same and cause a fresh export of the Ninja manifest.

**Comment by NiklasRosenstein** [comment]
Also, it would be nice if it would be possible to list actual files to build on the command-line. Like

    craftr build/myproject/main.exe

**Comment by winksaville** [comment]
Interesting, but it could be a rat hole, and lead you to implementing
another language. I suggest just a your high level "tasks ..." Invokable
Python.

My $.02.

**Comment by winksaville** [comment]
Let me try that last sentence again.

I suggest having your high level "tasks, variable, methods ..." invokable
and composable using Python.

;)

**Comment by NiklasRosenstein** [comment]
> I suggest having your high level "tasks, variable, methods ..." invokable
and composable using Python.

@wink Could you show an example on what you're thinking of?

I just solved the tasks thing on the command-line without `-f` or `-F` by introducing a new `task()` decorator. Functions wrapped with the `task()` function are exported to the Ninja manifest and can be specified on the command-line like any other targets and can also have dependencies, inputs and outputs.

**Comment by NiklasRosenstein** [comment]
Here's some more info on Tasks and RTS:

* http://craftr.readthedocs.io/en/latest/rts.html
* http://craftr.readthedocs.io/en/latest/api.html#craftr.task
