### ISSUE TITLE
Support Craftfile.py and .craftrc.py

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#95]
I think it might look more natural to have the `.py` suffix on these files since they essentially are Python files.

**Comment by winksaville** [comment]
+1

**Comment by NiklasRosenstein** [comment]
While we're at it, I suggest all the following changes to the file naming scheme:

| old name/scheme | new name/scheme |
| --- | --- |
| `Craftfile` | `Craftfile.py` |
| `.craftrc` | `craftrc.py` |
| `<some_module>.craftr` | `craftr.ext.<some_module>.py` |
