### ISSUE TITLE
Move options extension module to Craftr main module

### ISSUE THREAD

**Issue by NiklasRosenstein** [craftr-build/craftr#97]
Reading configuration values from the environment is a common necessity and should not require importing an additional Craftr extension module. Currently, convenient functions are available in `craftr.ext.options`. This issue proposes moving the module to `craftr.options` and include it in `craftr.__all__` so it will be imported automatically with `from craftr import *`.

**Comment by winksaville** [comment]
Is this documented? I'm wondering two things. First, it would be nice to
automatically include the options without needing to "import *". Secondly,
is there a command line flag to specify the config.option file so multiple
different option files can be created?

**Comment by NiklasRosenstein** [comment]
The way options are handled is quickly mentioned here: http://craftr.readthedocs.io/en/latest/#target-references-build-options

For now, importing the old `craftr.ext.options` module will display a warning until the deprecated module is removed completely.

> First, it would be nice to
automatically include the options without needing to "import *".

Not sure if I understand you right. I came to the conclusion that any symbols made " built-in" automatically. I prefer the explicit is better thsn implicit in this case and many others. So instead of having a global `options` symbol available by default, the user should import it from the craftr module

    from craftr import Framework, path, options # very explicit
    from craftr import *  # still better than not being required to put this line at all

> Secondly,
is there a command line flag to specify the config.option file so multiple
different option files can be created?

There might be a misunderstanding about options on your side (which might very well drive from the lack of good documentation). I am note sure what you mean by "multiple different option files". Options in Craftr are just environment variables. The `craftr.options.get()` function just has some convenient properties compared to reading the option directly using `getenv()` or `os.environ`.

**Comment by winksaville** [comment]
I want to be able to control what and how things are built based on
information provided at build time. For example building for ARM or x86,
Linux or windows or bare metal ... that's what I mean.

**Comment by NiklasRosenstein** [comment]
Whether you're building for Windows or Linux could be determined from your current operating system. That's in fact whats happening when you import a compiler/link from `craftr.ext.platform`.

    from craftr.ext.platform import cxx, ld

This will give you GCC on Linux, Clang on Mac and MSVC on Windows. There are some ways to override this behaviour, but if you really want to customize it, you have to do it yourself.

```python
from craftr import *
target = options.get('TargetPlatform')
if target == 'windows':
  from craftr.ext.compiler import msvc
  cc = msvc.MsvcCompiler('cl', 'c')
  ld = msvc.MsvcLinker()
elif target in ('linux', 'arm', 'x86', 'baremetal'):
  from craftr.ext import unix
  from craftr.ext.compiler import gcc
  if target == 'linux':
    cc = ld = gcc.GccCompiler('gcc', 'c')
  elif target == 'arm':
    cc = ld = gcc.GccCompiler('gcc-arm-4.7', 'c')
  elif target == 'x86':
    cc = ld = gcc.GccCompiler('gcc-x86-4.7', 'c')
  else:
    cc = ld = gcc.GccCompiler('gcc-baremetal-4.7', 'c')
else:
  error('invalid value for TargetPlatform: {!r}'.format(target))
```

And you'd run Craftr like

    craftr -eb -DTargetPlatform=arm

Note that if you're not cross-compiling, the compilers you can import from `craftr.ext.platform` read the `CC`, `CXX` environment variables already so you could just do

* `CC=gcc-arm-4.7 craftr -eb`, or
* craftr -eb -DCC=gcc-arm-4.7`

**Comment by winksaville** [comment]
K, txs
